import { $, asList, escapeHtml, fmtTime, setEmpty } from "../dom.js";
import {
  buildEfficiencyGroups, buildTaskMeta, clamp, computeEfficiencyKpis,
  efficiencyJitterOffset, fmtTokens, OSC_LOG_FLOOR,
  EFFICIENCY_MIN_PLOT_POINTS,
} from "../analytics/shared.js";

export class EfficiencyPanel {
  constructor({ state, documentRef = globalThis.document } = {}) { this.state = state; this.document = documentRef; }

  render(samples, tasks) {
    const chart = $("efficiencyChart", this.document); const kpis = $("efficiencyKpis", this.document); const legend = $("efficiencyLegend", this.document); const countEl = $("efficiencyCount", this.document);
    if (!chart || !kpis || !legend || !countEl) return;
    const empty = $("efficiencyEmpty", this.document); if (empty) empty.textContent = this.state.complexityBucket ? "No efficiency samples match the complexity filter." : "Efficiency data accumulates as todos are pruned with an actual complexity and their tasks report token usage.";
    const plottable = asList(samples).filter((sample) => sample.actual_complexity_num != null && Number(sample.total_tokens) > 0);
    const groups = buildEfficiencyGroups(plottable, (label) => this.state.colorFor(label)); const pointCount = groups.reduce((sum, group) => sum + group.samples.length, 0); const sparse = pointCount < EFFICIENCY_MIN_PLOT_POINTS;
    countEl.textContent = pointCount ? `${pointCount} sample${pointCount === 1 ? "" : "s"} · total tokens vs actual complexity` : ""; setEmpty("efficiencyEmpty", sparse, this.document);
    if (sparse) { chart.innerHTML = ""; kpis.innerHTML = ""; legend.innerHTML = ""; return; }
    kpis.innerHTML = computeEfficiencyKpis(groups).map((kpi) => { const biasText = kpi.calibrationBias == null ? "no planned estimates" : `bias ${kpi.calibrationBias >= 0 ? "+" : ""}${kpi.calibrationBias.toFixed(1)} CU`; const title = `${kpi.label}: median ${fmtTokens(kpi.medianPerUnit)} tokens per complexity unit over ${kpi.sampleCount} samples; planned-vs-actual calibration ${kpi.calibrationBias == null ? "unavailable (no planned estimates)" : `${biasText} over ${kpi.pairCount} pair${kpi.pairCount === 1 ? "" : "s"} (positive = underestimated)`}`; return `<div class="eff-kpi" data-model-label="${escapeHtml(kpi.label)}" title="${escapeHtml(title)}"><div class="eff-kpi-label"><span class="eff-swatch" style="background:${kpi.color}"></span>${escapeHtml(kpi.label)}</div><div class="eff-kpi-value">${escapeHtml(fmtTokens(kpi.medianPerUnit))}<span class="eff-kpi-unit muted">tok/CU</span></div><div class="eff-kpi-meta muted">${escapeHtml(biasText)} · ${kpi.sampleCount} samples</div></div>`; }).join("");
    legend.innerHTML = groups.map((group) => `<div class="donut-legend-item" data-model-label="${escapeHtml(group.label)}" role="button" tabindex="0"><span class="donut-swatch" style="background:${group.color}"></span><span class="donut-legend-label">${escapeHtml(group.label)}</span><span class="donut-legend-count muted">${group.samples.length}</span></div>`).join("");
    let chartGroups = groups; if (this.state.osc.selectedModel) { const only = groups.filter((group) => group.label === this.state.osc.selectedModel); if (only.length) chartGroups = only; }
    const taskMeta = buildTaskMeta(tasks, this.state.latest?.open_todos || []); const width = Math.max((($("efficiencyChart", this.document)?.clientWidth || 0) > 40 ? $("efficiencyChart", this.document).clientWidth : 640), 1); const height = 240; const padLeft = 52; const padRight = 16; const padTop = 12; const axisH = 22; const plotW = Math.max(width - padLeft - padRight, 1); const plotH = Math.max(height - padTop - axisH, 1);
    const xs = chartGroups.flatMap((group) => group.samples.map((sample) => sample.actual_complexity_num)); const xMin = Math.min(...xs) - 0.5; const xMax = Math.max(...xs) + 0.5; const xOf = (value) => padLeft + ((value - xMin) / (xMax - xMin)) * plotW;
    const clamped = chartGroups.flatMap((group) => group.samples.map((sample) => Math.max(Number(sample.total_tokens), OSC_LOG_FLOOR))); const tickLo = Math.floor(Math.log10(Math.min(...clamped))); const tickHi = Math.max(Math.ceil(Math.log10(Math.max(...clamped))), tickLo + 1); const logLo = tickLo * Math.LN10; const logHi = tickHi * Math.LN10; const yOf = (tokens) => { const norm = (Math.log(Math.max(tokens, OSC_LOG_FLOOR)) - logLo) / (logHi - logLo); return padTop + (1 - clamp(norm, 0, 1)) * plotH; };
    const xTicks = []; for (let value = Math.ceil(xMin); value <= Math.floor(xMax); value += 1) xTicks.push(`<line class="eff-grid" x1="${xOf(value).toFixed(2)}" y1="${padTop}" x2="${xOf(value).toFixed(2)}" y2="${(padTop + plotH).toFixed(2)}"></line><text class="eff-tick" x="${xOf(value).toFixed(2)}" y="${height - 6}" text-anchor="middle">${escapeHtml(["", "S", "M", "L", "XL"][value] || String(value))}</text>`);
    const yTicks = []; for (let power = tickLo; power <= tickHi; power += 1) { const y = yOf(10 ** power); yTicks.push(`<line class="eff-grid" x1="${padLeft}" y1="${y.toFixed(2)}" x2="${(width - padRight).toFixed(2)}" y2="${y.toFixed(2)}"></line><text class="eff-tick" x="${padLeft - 8}" y="${(y + 3).toFixed(2)}" text-anchor="end">${escapeHtml(fmtTokens(10 ** power))}</text>`); }
    const series = chartGroups.map((group) => { const dots = group.samples.map((sample) => { const x = xOf(sample.actual_complexity_num + efficiencyJitterOffset(`${sample.task_key}:${sample.agent_id}`)); const y = yOf(Number(sample.total_tokens)); const info = taskMeta.get(String(sample.task_key || "").toLowerCase()); const io = sample.input_tokens != null || sample.output_tokens != null ? `in ${fmtTokens(sample.input_tokens || 0)} / out ${fmtTokens(sample.output_tokens || 0)}` : ""; const lines = [`${group.label} · ${fmtTokens(sample.total_tokens)} tokens`, `actual ${sample.actual_complexity}${sample.planned_complexity ? ` · planned ${sample.planned_complexity}` : ""}`, io, fmtTime(sample.ts), sample.task_key, info?.title ? info.title : "", info?.summary ? info.summary : ""]; return `<circle class="eff-point" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="4.5" fill="${group.color}"><title>${escapeHtml(lines.filter(Boolean).join("\n"))}</title></circle>`; }).join(""); return `<g class="eff-series" data-model-label="${escapeHtml(group.label)}">${dots}</g>`; }).join("");
    chart.innerHTML = `<svg class="eff-svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Scatter of total tokens (log scale) against actual task complexity, colored by model">${xTicks.join("")}${yTicks.join("")}${series}</svg>`;
  }

  rerender(filterRows) { const data = this.state.latest; if (data) this.render(filterRows(data.efficiency_samples || []), filterRows(data.recent_tasks || [])); }
}
